# Use postgres/example as username/password
version: '3.8'

services:

  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
